repos:
  # black - Format python scripts
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11

  # flake8 - Python code linting
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8
        types: [python]
        args:
          - --max-line-length=88
          - --ignore=E203,E501,W503

  # isort - Imports sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  # pyupgrade - Automatically upgrade syntax for newer versions of the language
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.13.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus

  # mypy - Perform type checking on your code
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
